CREATE TABLE IF NOT EXISTS delivery_blocked_pincodes (
    pincode CHAR(6) PRIMARY KEY,
    reason VARCHAR(150) NOT NULL DEFAULT '',
    active TINYINT(1) NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

