CREATE TABLE IF NOT EXISTS products (
    id VARCHAR(64) PRIMARY KEY,
    slug VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(150) NOT NULL,
    category VARCHAR(80) NOT NULL,
    description VARCHAR(500) NOT NULL,
    price DECIMAL(10, 2) UNSIGNED NULL,
    variant VARCHAR(100) NOT NULL DEFAULT '',
    badge VARCHAR(60) NOT NULL DEFAULT '',
    benefits JSON NULL,
    image_url VARCHAR(500) NOT NULL DEFAULT '',
    alt_text VARCHAR(250) NOT NULL DEFAULT '',
    purchasable TINYINT(1) NOT NULL DEFAULT 0,
    track_stock TINYINT(1) NOT NULL DEFAULT 0,
    stock_quantity INT UNSIGNED NOT NULL DEFAULT 0,
    low_stock_threshold SMALLINT UNSIGNED NOT NULL DEFAULT 5,
    active TINYINT(1) NOT NULL DEFAULT 1,
    sort_order SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_products_active_sort (active, sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO products
    (id, slug, name, category, description, price, variant, badge, benefits, image_url, alt_text, purchasable, active, sort_order)
VALUES
    ('karupatti-500', 'pure-palm-jaggery', 'Pure Palm Jaggery', 'Karupatti',
     'A mineral-rich, traditionally prepared alternative to refined sugar.',
     420.00, '500 g', 'Natural sweetener', NULL,
     'assets/images/products/pure-palm-jaggery.jpg',
     'Natural palm jaggery prepared using traditional methods', 1, 1, 10),
    ('cow-butter-1kg', 'pure-cow-butter', 'Pure Cow Butter', 'Uthukuli butter',
     'Fresh, creamy butter made from premium cow''s milk for cooking and baking.',
     820.00, '1 kg · 2 × 500 g', 'Farm favourite', NULL,
     'https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?auto=format&fit=crop&w=900&q=80',
     'Fresh pure cow butter', 1, 1, 20),
    ('buffalo-butter-1kg', 'fresh-white-butter', 'Fresh White Butter', 'Uthukuli butter',
     'Soft buffalo butter with a naturally rich taste and no preservatives.',
     840.00, '1 kg · 2 × 500 g', 'Small batch', NULL,
     'https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?auto=format&fit=crop&w=900&q=80',
     'Fresh white buffalo butter', 1, 1, 30),
    ('cow-ghee-1l', 'traditional-cow-ghee', 'Traditional Cow Ghee', 'Cow ghee',
     'Slow-cooked from fresh cow butter for a deep aroma and authentic flavour.',
     1020.00, '1 litre · 2 × 500 ml', 'Best seller', NULL,
     'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=900&q=80',
     'Traditional slow-cooked cow ghee', 1, 1, 40),
    ('buffalo-ghee-1l', 'village-style-ghee', 'Village-Style Ghee', 'Buffalo ghee',
     'Full-bodied buffalo ghee, prepared traditionally for a rich, grainy texture.',
     1050.00, '1 litre · 2 × 500 ml', 'Village style', NULL,
     'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=900&q=80',
     'Village-style buffalo ghee', 1, 1, 50),
    ('peanut-oil', 'wood-pressed-peanut-oil', 'Wood-Pressed Peanut Oil', 'Cooking oil',
     'Pure cold-pressed groundnut oil with its natural aroma, flavour and healthy fats preserved. Chemical-free and ideal for everyday Indian cooking.',
     NULL, 'Pack sizes available', 'Wood pressed',
     JSON_ARRAY('Cold pressed', 'No preservatives', 'Traditional flavour'),
     'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=900&q=80',
     'Cold pressed groundnut oil made using a traditional wood press', 0, 1, 60),
    ('coconut-oil', 'wood-pressed-coconut-oil', 'Wood-Pressed Coconut Oil', 'Coconut oil',
     'Made from selected coconuts using a traditional wood press. This pure coconut oil retains its natural aroma and is suitable for cooking, hair and skin care.',
     NULL, 'Pack sizes available', 'Multipurpose',
     JSON_ARRAY('Cold pressed', 'Chemical free', 'Hair and skin care'),
     'https://images.unsplash.com/photo-1525904097878-94fb15835963?auto=format&fit=crop&w=900&q=80',
     'Pure cold pressed coconut oil for cooking, hair and skin care', 0, 1, 70),
    ('sesame-oil', 'wood-pressed-sesame-oil', 'Wood-Pressed Sesame Oil', 'Gingelly oil',
     'Pure gingelly oil prepared by the traditional wood-press method to preserve the aroma and goodness of sesame seeds. Excellent for authentic cooking.',
     NULL, 'Pack sizes available', 'Traditional',
     JSON_ARRAY('Cold pressed', 'Natural antioxidants', 'Authentic taste'),
     'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=900&q=80',
     'Traditional wood pressed sesame oil also known as gingelly oil', 0, 1, 80),
    ('lamp-oil', 'pure-lamp-oil', 'Pure Lamp Oil', 'Lamp oil',
     'Quality pooja oil made for daily lamps at home and in temples. Designed for a clean, steady flame with low smoke and a longer burning time.',
     NULL, 'Pack sizes available', 'Pooja essential',
     JSON_ARRAY('Long burning', 'Low smoke', 'For home and temple'),
     'https://images.unsplash.com/photo-1604608672516-f1b9b1d37076?auto=format&fit=crop&w=900&q=80',
     'Pure long-burning lamp oil for pooja and traditional lamps', 0, 1, 90),
    ('turmeric-powder', 'natural-turmeric-powder', 'Natural Turmeric Powder', 'Turmeric powder',
     'Quality turmeric roots, hygienically dried and finely ground into pure turmeric powder with a naturally rich colour and aroma for everyday cooking.',
     NULL, 'Pack sizes available', 'Kitchen essential',
     JSON_ARRAY('Natural colour', 'No chemical additives', 'Finely ground'),
     'https://images.unsplash.com/photo-1615485500704-8e990f9900f7?auto=format&fit=crop&w=900&q=80',
     'Natural pure turmeric powder rich in curcumin', 0, 1, 100),
    ('organic-soap', 'handmade-organic-soap', 'Handmade Organic Soap', 'Organic soap',
     'A gentle herbal soap made with plant oils and natural ingredients. Free from parabens, sulphates and artificial fragrance, and suitable for all skin types.',
     NULL, 'Variants available', 'Handmade',
     JSON_ARRAY('Paraben free', 'Sulphate free', 'All skin types'),
     'https://images.unsplash.com/photo-1600857544200-b2f666a9a2ec?auto=format&fit=crop&w=900&q=80',
     'Handmade organic herbal soap made with plant oils', 0, 1, 110)
ON DUPLICATE KEY UPDATE
    slug = VALUES(slug),
    name = VALUES(name),
    category = VALUES(category),
    description = VALUES(description),
    price = VALUES(price),
    variant = VALUES(variant),
    badge = VALUES(badge),
    benefits = VALUES(benefits),
    image_url = VALUES(image_url),
    alt_text = VALUES(alt_text),
    purchasable = VALUES(purchasable),
    active = VALUES(active),
    sort_order = VALUES(sort_order);
